<?php

namespace Omnipay\Epay\Message;

use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Common\Message\NotificationInterface;

/**
 * Class NotifyResponse
 * @package Omnipay\Epay\Message
 */
class NotifyResponse extends AbstractResponse implements NotificationInterface
{
    const STATUS_CANCELLED = 'cancelled';
    const STATUS_TIMEOUTED = 'timeouted';

    /**
     * @return bool
     */
    public function isSuccessful()
    {
        return isset($this->data['status']);
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return isset($this->data['invoice']) ? $this->data['invoice'] : null;
    }

    /**
     * @return string
     */
    public function getTransactionStatus()
    {
        if (!isset($this->data['status'])) {
            return static::STATUS_FAILED;
        }

        switch ($this->data['status']) {
            case 'PAID':
                return static::STATUS_COMPLETED;
            case 'DENIED':
                return static::STATUS_CANCELLED;
            case 'EXPIRED':
                return static::STATUS_TIMEOUTED;
            default:
                return static::STATUS_FAILED;
        }
    }
}
